name: rendersynth_download
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python==3.10.11
  - nginx==1.25.0
  - pip
  - pip:
    - lightning
    - wandb==0.13.10
    - tensorboard==2.11.0
    - pandas==1.5.2
    - seaborn==0.12.2
    - gdown==4.4.0
    - opencv-python-headless<4.0
    - transformers==4.28.1
    - pillow==9.4.0
    - scipy==1.10.0
    - torchmetrics==0.11.0
    - scikit-learn==1.2.0
    - scikit-image==0.19.3
    - matplotlib
    - numpy
    - torchgeo
    #version 3
    - webdataset==0.2.33
    - braceexpand==0.1.7
    #version 5
    - h5py
    - ipykernel
    #download
    - geopandas
    - shapely
    - requests
    - osmnx
    - mercantile
    - geojson
    - timeout_decorator
